import "./styles/home/8e627451e5f1507d.css";
import "./styles/home/b8e302d41b271438.css";
import "./styles/home/slider.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
